/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('users').del()
  await knex('users').insert([
    {name: 'Amanda G Owens', email: 'orville1972@gmail.com',password: 'password1',city: 'Holmesville,',state: 'Ohio',smoking_preference: true,pronouns: 'She/Her',looking_for: 'Casual relationship',age: '32',bio: 'My husband is cheating on me and I need a new soulmate. This seems like the only successful path.',profile_pic: 'https://randomuser.me/api/portraits/men/4.jpg',ethnicity: 'Asian',religion: 'Catholic',children: false,pets: true},
    {name: 'John V Price', email: 'clifford1990@yahoo.com',password: 'password2',city: 'Murray,',state: 'Utah',smoking_preference: true,pronouns: 'He/Him',looking_for: 'Serious relationship',age: '22',bio: 'Maya Angelou once said, “I know why the caged bird sings”. I dont know what this has to do with anything, but I got your attention huh?',profile_pic: 'https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YmxhY2slMjBwZXJzb258ZW58M',ethnicity: 'Black/African descent',religion: 'Christian',children: false,pets: false},
    {name: 'Justin M Page', email: 'axel2001@hotmail.com',password: 'password3',city: 'Rancho California,',state: 'California',smoking_preference: false,pronouns: 'He/Him',looking_for: 'Marriage',age: '30',bio: 'Social media buff. Professional entrepreneur. Web junkie. Travel guru. ',profile_pic: 'https://assets.teenvogue.com/photos/5c3fb4b2360bd63de9435f4c/1:1/w_1022,h_1022,c_limit/IMG_3207.JPG',ethnicity: 'Black/African descent',religion: 'Christian',children: true,pets: true},
    {name: 'Felix M Palmer', email: 'noemie.harb@hotmail.com',password: 'password4',city: 'Baraga,',state: 'Michigan',smoking_preference: true,pronouns: 'He/Him',looking_for: 'Casual relationship',age: '25',bio: 'Music practitioner. Entrepreneur. Web fan. Communicator. Internet fanatic. Food scholar.',profile_pic: 'https://cdns3.clover.co/mxr_photos/20/6b/206bed2edc7133a8cf5ef02d5fe63ced/5dqC00a_1606058349.8838.jpg',ethnicity: 'Latino/Hispanic',religion: 'Catholic',children: false,pets: true},
    {name: 'Donald A Ellzey', email: 'elnora2014@gmail.com',password: 'password5',city: 'Saginaw,',state: 'Michigan',smoking_preference: false,pronouns: 'He/Him',looking_for: 'Friendship',age: '27',bio: 'Social mediaholic. Food enthusiast. Amateur entrepreneur. Bacon junkie. Creator. Internet fanatic.',profile_pic: 'https://images.theconversation.com/files/345679/original/file-20200705-33913-11gs847.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop',ethnicity: 'Black/African descent',religion: 'Christian',children: true,pets: false},
    {name: 'George E Martin', email: 'myriam1997@yahoo.com',password: 'password6',city: 'San Diego,',state: 'California',smoking_preference: true,pronouns: 'He/Him',looking_for: 'Casual relationship',age: '39',bio: 'Alcohol fanatic. Travel trailblazer. Creator.',profile_pic: 'https://therapyforblackmen.org/wp-content/uploads/2020/09/image1-06292018-300x300-1.jpeg',ethnicity: 'Black/African descent',religion: 'Catholic',children: false,pets: true},
    {name: 'Sandra S Higgins', email: 'SandraHiggins@gmail.com',password: 'password7',city: 'San Angelo,',state: 'Texas',smoking_preference: false,pronouns: 'They/Them',looking_for: 'Travel partner',age: '21',bio: 'My back hurts from carrying all this sexiness around.',profile_pic: 'https://media.istockphoto.com/photos/young-woman-at-summer-pool-party-taking-selfie-on-mobile-phone-picture-id1227327055?k=20&m=1227327055&s=612x612&w=0&h=MiMmtOUNBCZAvx5DtAFKeG5DKa-UPOLXaX8NEhbGC9Y=',ethnicity: 'Black/African descent',religion: 'Other',children: false,pets: false},
    {name: 'Kelly M Smith', email: 'KellySmith@gmail.com',password: 'password8',city: 'Hagerstown,',state: 'Maryland',smoking_preference: true,pronouns: 'She/Her',looking_for: 'Casual relationship',age: '30',bio: 'As time goes on, all I have left is to think of you!',profile_pic: 'https://i.pinimg.com/736x/34/59/e7/3459e79bc1e79af0919271d063ff7490.jpg',ethnicity: 'Native American',religion: 'Christian',children: true,pets: true},
    {name: 'Lisa M Culpepper', email: 'LisaCulpepper@gmail.com',password: 'password9',city: 'Hartford,',state: 'Connecticut',smoking_preference: false,pronouns: 'She/Her',looking_for: 'Friendship',age: '29',bio: 'Wyd tonight? Trying to go on a date and find someone new. ',profile_pic: 'https://t3.ftcdn.net/jpg/02/38/73/22/360_F_238732219_8dSOVcoGmop1kT6zpLVIMDdjcfrBvG3t.jpg',ethnicity: 'Asian',religion: 'Other',children: true,pets: true},
    {name: 'Grace F Kimble', email: 'GraceKimble@gmail.com',password: 'password10',city: 'Altoona,',state: 'Pennsylvania',smoking_preference: true,pronouns: 'She/Her',looking_for: 'Serious relationship',age: '30',bio: 'Looking for a suitor who will meet my needs of finding love and providing an heir. My mother is one of the most respected fashion designers in the industry. Ive influenced people like Naomi Campbell, Barack Obama and Kris Jenner through fashion. Love hanging out with my best friends Serena and Nate at the Met',profile_pic: 'https://clairegallowayblog.files.wordpress.com/2017/08/img_20170806_175121.jpg?w=840',ethnicity: 'White',religion: 'Muslim',children: false,pets: true},
    
    {name: 'Beth A Griffin', email: 'BethGriffin@gmail.com',password: 'password1',city: ' Minneapolis,',state: 'Minnesota',smoking_preference: true,pronouns: 'They/Them',looking_for: 'Casual relationship',age: '30',bio: 'Im a party promoter from Minneapolis, living my best life. Hit me up if you want to party and more!',profile_pic: 'https://img.freepik.com/free-photo/asian-beautiful-woman-make-selfie_273609-2692.jpg?w=2000',ethnicity: 'Asian',religion: 'Catholic',children: false,pets: true},
    {name: 'Craig M Gill', email: 'CraigGill@yahoo.com',password: 'password2',city: 'Tulsa,',state: 'Oklahoma',smoking_preference: true,pronouns: 'He/Him',looking_for: 'Serious relationship',age: '22',bio: 'A Staff Software Engineer at Zendesk. I love to read books, go on long walks on the beach, and try new things. Would love to snuggle up and go on an Abbott Elementary binge.',profile_pic: 'https://cdn.pixabay.com/photo/2019/12/16/14/46/black-man-4699505_960_720.jpg',ethnicity: 'Black/African descent',religion: 'Christian',children: false,pets: false},
    {name: 'Steven T Hannah', email: 'StevenHannah@hotmail.com',password: 'password3',city: 'Atlanta,',state: 'Georgia',smoking_preference: false,pronouns: 'He/Him',looking_for: 'Marriage',age: '30',bio: 'I believe that Princess Di is still alive. If you believe so too, lets match.',profile_pic: 'https://images.unsplash.com/photo-1612214070475-1e73f478188c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fGJsYWNrJTIwbWFufGVufDB8fDB8fA%3D%3D&w=1000&q=80',ethnicity: 'Black/African descent',religion: 'Christian',children: true,pets: true},
    {name: 'Martha M Blackshear', email: 'MarthaBlackshear@hotmail.com',password: 'password4',city: 'Maumee,',state: 'Ohio',smoking_preference: true,pronouns: 'She/Her',looking_for: 'Casual relationship',age: '37',bio: 'Star Wars fanatic. I have a persistent enthusiasm to create new things.',profile_pic: 'https://1k664ijmb5e1crjox1eersr1-wpengine.netdna-ssl.com/images/hispanic-mail-order-brides.jpg',ethnicity: 'Latino/Hispanic',religion: 'Catholic',children: false,pets: true},
    {name: 'Jack L Ernest', email: 'JackErnest@gmail.com',password: 'password5',city: 'Wausau,',state: 'Wisconsin',smoking_preference: false,pronouns: 'He/Him',looking_for: 'Friendship',age: '27',bio: 'I like jazz music and bacon. Learning new things is one of my obsessions.',profile_pic: 'https://i.pinimg.com/originals/01/3f/83/013f8354f3f80c1481d25dee4d513806.jpg',ethnicity: 'Black/African descent',religion: 'Christian',children: true,pets: false},
    {name: 'James T Cox', email: 'JamesCox@yahoo.com',password: 'password6',city: 'Washington,',state: 'Kansas',smoking_preference: true,pronouns: 'He/Him',looking_for: 'Casual relationship',age: '39',bio: 'I see video and web as a way to reach and inspire people.',profile_pic: 'https://i.pinimg.com/originals/23/be/25/23be25291d3c3f5318db38942bb91417.jpg',ethnicity: 'Black/African descent',religion: 'Catholic',children: false,pets: true},
    {name: 'Yolanda M Vigna', email: 'YolandaVigna@gmail.com',password: 'password7',city: 'Portland,',state: 'Pennsylvania',smoking_preference: false,pronouns: 'She/Her',looking_for: 'Travel partner',age: '30',bio: 'Unapologetic reader and proud communicator. Bacon and coffee everyday.',profile_pic: 'https://i.pinimg.com/originals/8e/2c/18/8e2c180c188bab6e4adcaf9b95ca51f0.jpg',ethnicity: 'Black/African descent',religion: 'Other',children: false,pets: false},
    {name: 'Latricia C Shedd', email: 'LatriciaShedd@gmail.com',password: 'password8',city: 'Schaumburg,',state: 'Illinois',smoking_preference: true,pronouns: 'She/Her',looking_for: 'Casual relationship',age: '25',bio: 'I have a huge passion for food, hate to stay in comfort zone.',profile_pic: 'https://i.cbc.ca/1.4981075.1547749218!/fileImage/httpImage/image.jpg_gen/derivatives/original_780/louise-bigeagle.jpg',ethnicity: 'Native American',religion: 'Christian',children: true,pets: true},
    {name: 'Cameron N Amis', email: 'CameronAmis@gmail.com',password: 'password9',city: 'Beltsville,',state: 'Maryland',smoking_preference: false,pronouns: 'They/Them',looking_for: 'Friendship',age: '29',bio: 'Originally from California. Half gamer and wine drinker.',profile_pic: 'https://i.pinimg.com/originals/21/fd/17/21fd1734005875b0fa65c0ef96f3afad.jpg',ethnicity: 'Asian',religion: 'Other',children: true,pets: true},
    {name: 'Harold M Laury', email: 'HaroldLaury@gmail.com',password: 'password10',city: 'Roanoke,',state: 'Virginia',smoking_preference: true,pronouns: 'He/him',looking_for: 'Serious relationship',age: '39',bio: 'Currently in love with cycling. Obsessed with creating helpful stuff.',profile_pic: 'https://us.123rf.com/450wm/sevendeman/sevendeman2001/sevendeman200100083/137857963-happy-asian-man-selfie-in-his-condominium-room-.jpg?ver=6',ethnicity: 'Asian',religion: 'Other',children: false,pets: true}
  ])
  };
